### ISSUE TITLE
This application is not an Angular application

### ISSUE THREAD

**Issue by Stefjoe** [rangle/augury#1232]
Augury: 1.14.0
Date: Mon, 21 Aug 2017 07:38:20 GMT
OS: MacIntel

Demo test application:
-- Git repository for demo app showing the issue (optional but very helpful for difficult issues).
-- If a code snippet will completely show the issue, please include it.

Description of issue:
-- Include (clipped) screenshot images if possible.

Angular version (required): 4 -> latest

Steps to reproduce:

1.  Learning the quickstart tutorial -> https://angular.io/guide/quickstart
2. Follow the steps
3. Augury console -> This application cannot be inspected using Augury

Additional details: 
Also on Windows Chrome it is not working

**Comment by arafeek** [comment]
Hi @Stefjoe, thanks for your feedback! If you don't mind my asking, what stage of the tutorial are you in when you are trying to inspect with Augury? The application needs to be successfully running in order for Augury to properly recognize the application.

**Comment by Stefjoe** [comment]
Hi @arafeek,

thx for your reply :-) 

I installed Augury when i was at the tut point Services:
https://angular.io/tutorial/toh-pt4

It ist strange, because sometimes it is working an sometimes not, i am using Angular version 4.3.5.
I must also say, that i am totally new to Angular, so maybe it could also be a user mistake, don't really know. 

When i start **npm start** and open the console, it doesn't work. When i start **npm start** again and open the console it seems to be working.

Rgds

**Comment by theship** [comment]
Hi, folks: Just FYI, I got the same error message on a sample file as well, but it happened when I messed with the files. I was running the sample app for the reactive forms (https://angular.io/guide/reactive-forms). I corrupted the systemjs-angular-loader.js file. Once I corrected the mistake, the error went away.

**Comment by davidrdz93** [comment]
using angular-cli 1.3.2 same problem. My angular app is running normally but Angury doesn't recognize it!

**Comment by abdulkareemnalband** [comment]
Can we have a button to reload augury on this error?
Whenever we go through a login workflow for oauth in our app augury fails to recognize angular app

**Comment by liqwid** [comment]
I believe the problem is in frontend part of augury: backend.js is getting injected while I still get "This application cannot be inspected using Augury" screen.

Found a hack to reload Augury:
Valid for new versions of chrome(>=61)
1. Right click and inspect Augury tab(that's only possible in newer versions of chrome)
2. Focus augury devtools.
3. Reload page

For me that helps to reload Augury frontend state and everything works from that point until a page reload.

**Comment by SangKa** [comment]
![image](https://user-images.githubusercontent.com/6177271/33700853-98012abc-db56-11e7-94bc-45e357d94f70.png)

The primitive project that Angular CLI created got this problem.

Angular CLI: 1.5.3
Node: 8.9.0
OS: win32 x64
Chrome: 62

**Comment by dylanvb0** [comment]
I think I figured out the behavior. Whenever the project fails to build, it gives the screen as expected; however, when the application starts working again, that screen remains there. The solution is like @liqwid suggested. It just needs to be reloaded. I'm not sure if chrome updated since his comment, but the third step should be "Reload Frame".

**Comment by pharazon** [comment]
I didn't get Augury to recognize out of 2/2 angular 1.x sites that I tested that either would be angular -sites, so I installed ng-inspector instead.

**Comment by santiago-elustondo** [comment]
Anyone who is still having this issue: can you try using the [Canary Build](https://chrome.google.com/webstore/detail/augury-canary-build/leechohfifidanmkioncamdcibhmmcji) ?
Does the problem persist there, or is it resolved for you?

**Comment by andrewthauer** [comment]
Closing with the assumption this has been fixed. Please re-open with additional details if this is not the case.
