### ISSUE TITLE
State of component is not displaying

### ISSUE THREAD

**Issue by ajsuvarna6** [rangle/augury#903]
Augury is a very good tool while developing angular 2 application. But the problem is, it doesn't display state of component. For some components it is showing state, but then some components it doesn't show state. Only dependency is displayed.

**Comment by stevenkampen** [comment]
@ajsuvarna6 Can you provide an example repo or plunker where this occurs? That symptom has been reported (but not seen by me) when the router is injected into the component. Is this the case?

**Comment by jd-nfreitas** [comment]
It seems to depend on the dependencies. Having MdDialog (Angular Material2) listed as a dependency for a component will make state not show up for the component on Augury 1.2.7.

**Comment by ammarhaider7** [comment]
@stevenkampen I'm experiencing the same thing only for components where I'm injecting router..

**Comment by irackley-mc** [comment]
@stevenkampen I'm seeing the same when using ngTemplateOutlet. The component loses all properties in the viewer. I'll see if I can get a plunker together, but I first ran across it while running ngx-datatable locally and viewing one of their tabs that uses ngTemplateOutlet i.e. Row Detail under Basic. 
https://github.com/swimlane/ngx-datatable
Unfortunately their demo page is run in prod mode so you have to run it locally.

**Comment by stevenkampen** [comment]
@irackley-mc Thanks for your report. I'll get on this shortly and let you know when it's done.

**Comment by stevenkampen** [comment]
Ok I can recreate this now and confirm it's an issue with serialization/deserialization of some complex objects. Looking into it.

**Comment by stevenkampen** [comment]
This is fixed now in version 1.2.9, which was just released.

**Comment by rsksmiles** [comment]
Hi I seem to have this problem aswell but I have 1.4.0

**Comment by prasanna-kumar** [comment]
Yes, I'm getting same problem with 1.4.0

**Comment by raydaim** [comment]
@stevenkampen,  I am still having the same problem with 1.5.0

**Comment by stevenkampen** [comment]
@irackley-mc This is fixed for you now right? I see state for all components I could find in that application you shared.

**Comment by stevenkampen** [comment]
@prasanna-kumar @raydaim If this is persisting for you, can you open a new issue (after checking one doesn't already exist that fits what you're seeing)?

**Comment by irackley-mc** [comment]
@stevenkampen It has been working for me since your fix. My guess is the new reports are related but not the same exact issue, although I haven't tried out Angular 4 at all.

**Comment by stevenkampen** [comment]
@irackley-mc Yes, that's the case here. Several things can screw up serialization apparently so I'm hunting them down one by one. Thanks for your report!

**Comment by NikxDa** [comment]
I am having the same problem, using Augury 4.3.6 - any update on this?

**Comment by kostia-lev** [comment]
having same issue
https://gyazo.com/8c5583c88dd9c20ce2460d855f4045c0
with canary build and usual augury 1.17

**Comment by santiago-elustondo** [comment]
Howdy, @kostia-lev 

This issue is caused by numerous edge cases, many of which (although possibly not all) have been identified and fixed for in the latest [Canary](https://chrome.google.com/webstore/detail/augury-canary-build/leechohfifidanmkioncamdcibhmmcji) (version 1.17.4), released yesterday.

Can you confirm you are still seeing this issue in Canary version 1.17.4 ?

**Comment by tkstang** [comment]
Still having this issue with 1.19.1

**Comment by tinyweasel** [comment]
Happening me with 1.21.0

**Comment by NikxDa** [comment]
How is this still an issue after nearly two years?! Displaying state on all occasions should be basic functionality and #1 priority if broken!
